sonar.projectKey=natishg-1632006_E-commerce
sonar.organization=natishg-1632006

sonar.sources=e-com_backend

sonar.exclusions=**/node_modules/**,**/coverage/**,**/.serverless/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=e-com_backend/analytics-service/coverage/lcov.info,e-com_backend/cart-service/coverage/lcov.info,e-com_backend/category-service/coverage/lcov.info,e-com_backend/cognito-trigger-service/coverage/lcov.info,e-com_backend/coupon-service/coverage/lcov.info,e-com_backend/inventory-service/coverage/lcov.info,e-com_backend/notification-service/coverage/lcov.info,e-com_backend/order-service/coverage/lcov.info,e-com_backend/payment-service/coverage/lcov.info,e-com_backend/product-service/coverage/lcov.info,e-com_backend/user-service/coverage/lcov.info,e-com_backend/wishlist-review-service/coverage/lcov.info