sonar.projectKey=natishg-1632006_E-commerce
sonar.organization=natishg-1632006

sonar.sources=e-com_backend
sonar.tests=e-com_backend
sonar.test.inclusions=**/tests/**,**/*.test.js,**/*.spec.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/.serverless/**,**/dist/**,**/build/**,**/tests/**,**/*.test.js,**/*.spec.js
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*