service: coupon-service

frameworkVersion: "3"

provider:
  tracing:
    lambda: true
    apiGateway: true
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'ap-south-2'}
  stage: dev

  environment:
    NODE_ENV: production
    DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME, 'natish_coupons'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${env:DYNAMODB_TABLE_NAME, 'natish_coupons'}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${env:DYNAMODB_TABLE_NAME, 'natish_coupons'}/index/*

functions:
  app:
    handler: lambda.handler
    memorySize: 512
    timeout: 30

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

      - httpApi:
          path: /
          method: ANY
