service: cognito-trigger-service

frameworkVersion: "3"

provider:
  tracing:
    lambda: true
    apiGateway: true
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'ap-south-2'}
  stage: ${env:STAGE, 'dev'}
  environment:
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID, 'ap-south-2_AekUQ0VVq'}
    DEFAULT_GROUP: ${env:DEFAULT_GROUP, 'Customer'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'INFO'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminAddUserToGroup
          Resource:
            - arn:aws:cognito-idp:${self:provider.region}:*:userpool/${env:COGNITO_USER_POOL_ID, 'ap-south-2_AekUQ0VVq'}

functions:
  postConfirmationTrigger:
    handler: lambda.handler
    memorySize: 256
    timeout: 30
