service: analytics-service

frameworkVersion: "3"

provider:
  tracing:
    lambda: true
    apiGateway: true
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'ap-south-2'}
  stage: dev

  environment:
    NODE_ENV: production
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID, 'ap-south-2_AekUQ0VVq'}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, '2osrvmtu0c57dhvgr6ive13but'}
    INTERNAL_SERVICE_KEY: ${env:INTERNAL_SERVICE_KEY, ''}
    ORDER_SERVICE_URL: ${env:ORDER_SERVICE_URL, ''}
    PRODUCT_SERVICE_URL: ${env:PRODUCT_SERVICE_URL, ''}
    CATEGORY_SERVICE_URL: ${env:CATEGORY_SERVICE_URL, ''}
    INVENTORY_SERVICE_URL: ${env:INVENTORY_SERVICE_URL, ''}
    PAYMENT_SERVICE_URL: ${env:PAYMENT_SERVICE_URL, ''}
    COUPON_SERVICE_URL: ${env:COUPON_SERVICE_URL, ''}

functions:
  app:
    handler: lambda.handler
    memorySize: 512
    timeout: 30

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

      - httpApi:
          path: /
          method: ANY
